stages:
  - package
  - build
  - deploy

pakage_job:
  stage: package
  image: maven:latest
  allow_failure: false
  script:
    - echo "Maven package "
    - cd app 
    - mvn clean package
  artifacts:
    paths:
      - app/target/rentcar-0.0.1-SNAPSHOT.jar

build_job:
  stage: build
  image: python:latest
#  only :
#    refs:
#      - main
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - aws s3 cp app/target/rentcar-0.0.1-SNAPSHOT.jar $AWS_S3_BACK/rentcar-0.0.1-SNAPSHOT.jar
  artifacts:
    paths:
      - app/target/rentcar-0.0.1-SNAPSHOT.jar

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-118-11-217.us-east-2.compute.amazonaws.com "aws s3 cp s3://grupro03-back/rentcar-0.0.1-SNAPSHOT.jar console-app; sudo systemctl start consoleapp.service"
    - echo "Finished deploying the app."

